# Generated by Django 3.0.4 on 2020-03-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='repassword',
            field=models.CharField(default='', max_length=254),
        ),
    ]
